// Generated by scripts/import-ascii-lookalikes.mjs from confusable-vision release 2026.09.26 (in-place.jsonl.gz). Do not edit by hand.
/** ASCII strings that pass for one another: a (one or two characters) and b (one), the share of ten renderings (five
 * common fonts at text size, at 1x and 2x) where they are alike, and the font where they are closest. */
export const ASCII_LOOKALIKES: { a: string; b: string; share: number; font: string }[] = [{"a":"0","b":"o","share":0.2,"font":"Georgia 16"},
  {"a":"1","b":"l","share":0.2,"font":"Times New Roman 16"},
  {"a":"rn","b":"m","share":0.1,"font":"Arial 16"}];
